Feature/arrays home work
poluni/TMS_Auto pull request #2
Opened 2023-11-23 11:16 UTC by poluni

2023-11-27 18:11 UTC, wildpioneer requested changes

2023-11-27 18:11 UTC, wildpioneer commented on Task2_1/Program.cs
> +            for (int i = 0; i <= array.GetUpperBound(0); i++)
Перед for нужна пустая строка для более комфортного чтения кода.

2023-11-27 18:11 UTC, wildpioneer commented on Task2_2/Program.cs
> +            int[] OutputArray(int[] array)
Не заметил использования возвращаемого значения данного метода - а следовательно он должен быть void

2023-11-27 18:11 UTC, wildpioneer commented on Task2_3/Program.cs
> +            int Max(int[] array)
Технически верно - однако min и max можно найти за один прогон. Но так как ты реализовала это методами - то нет проблем - пусть будет так.

2023-11-27 18:11 UTC, wildpioneer commented on Task2_3/Program.cs
> +                return (double)sum / (array.GetLength(0));
Технически это среднее арифметическое значение - а не среднее.
1 5 10  - тут среднее будет 5 - а арифметическое среднее 5.3 ;)

2023-11-27 18:11 UTC, wildpioneer commented on Task2_6/Program.cs
> +            int[] newArray = new int[array.GetLength(0)];
А про новый массив в задаче ничего не говориться.

2023-11-27 18:11 UTC, wildpioneer commented on Task29/Program.cs
> +                    Console.Write($" {matrixResult[i, j]} ");
В результате - твоя результирующая матрица будет выведена только в строку?

2023-11-27 19:22 UTC, wildpioneer requested changes

2023-11-27 19:22 UTC, wildpioneer commented on Task2_6/Program.cs
> +                if (i % 2 != 0)
В условии не четный элемент - а четный индекс ;)

2023-12-01 11:23 UTC, poluni commented on Task29/Program.cs
> +                    Console.Write($" {matrixResult[i, j]} ");
Да. Реализация в соответствии с  примером вывода из задачи: "Ожидаемый результат: 1 2 3 1 1 1 0 0 0".

2023-12-01 11:41 UTC, poluni commented on Task2_1/Program.cs
> +            for (int i = 0; i <= array.GetUpperBound(0); i++)
Исправлено в 1996407b6b37e5a3cef6e79fd802549acf5c0908

2023-12-01 11:52 UTC, poluni commented on Task2_2/Program.cs
> +            int[] OutputArray(int[] array)
Исправлено в 5d048c143ba027f75d95ac17a9c46a34d0b1e519

2023-12-01 14:20 UTC, poluni commented on Task2_3/Program.cs
> +                return (double)sum / (array.GetLength(0));
Исправлено в fcad92744f645bfc6b78ee11c0d3ba4139b59313

2023-12-01 14:40 UTC, poluni commented on Task2_6/Program.cs
> +            int[] newArray = new int[array.GetLength(0)];
Исправлено в 231deec6e38b0129929fc79d797c4b38620b06ea

2023-12-01 14:40 UTC, poluni commented on Task2_6/Program.cs
> +                if (i % 2 != 0)
Исправлено в 231deec6e38b0129929fc79d797c4b38620b06ea

2024-01-29 10:09 UTC, wildpioneer commented
Проверено

2024-01-29 10:09 UTC, closed without merging