Feature/strings home work
poluni/TMS_Auto pull request #3
Opened 2023-11-25 17:12 UTC by poluni

2023-11-27 18:32 UTC, wildpioneer requested changes

2023-11-27 18:32 UTC, wildpioneer commented on Task31/Program.cs
> +            FileInfo fileInfo = new FileInfo(@"D:\git-auto\TMS_Auto\Task31\data.txt");
Для начала пойдет - но не совсем верно - потому как у меня не работает такое

2023-11-27 18:32 UTC, wildpioneer commented on Task31/Program.cs
> +                    reoplacedLine = line.Replace("test", "testing");
Явно перед коммитом символ вставила нечаянно - потому как у тебя нет такой объявленный переменной

2023-11-27 18:32 UTC, wildpioneer commented on Task34/Program.cs
> +            int positionOfRemove = inputLine.Length - removeWord.Length;
Тут я даже не совсем понимаю что происходит. 
Попробуй протестировать свое решение на строке 
string inputLine = "Плохой день."; ///После точки добавь 10 пробелов - GitHub удаляет не могу правильно вписать значение ;)
 
И все посыпется - а не должно

2023-11-27 18:32 UTC, wildpioneer commented on Task35/Program.cs
> +                 else
Форматирование - else не выровнен

2023-11-27 18:32 UTC, wildpioneer commented on Task35/Program.cs
> +                foreach (Match matchItem in matches)
Перед циклами - пустая строка
Перед IF - пустая строка

Поправь по файлу везде

2023-11-27 18:32 UTC, wildpioneer commented on Task35/Program.cs
> +                    else Console.WriteLine();
Если else в одну строку - то почему if - в блоке?

2023-11-27 18:32 UTC, wildpioneer commented on Task36/Program.cs
> +                        string word = sb.Replace("\t", " ").Replace("  ", " ").ToString();
Как простое решение - приму. Но все же в идеале:
нормализованная строка, это в которой нет дублирующих пробелов совсем. Если в твой файл с текстом между некоторыми словами вбить 5 пробелов - то после выполнения программы останется 3 - а это же не совсем корректно. Будет время - подумай как исправить

2023-11-27 18:32 UTC, wildpioneer commented on Task37/Program.cs
> +                string[] words = new string[] { };
new string[] - можно убрать - так как ты явно задаешь пустой массив

2023-11-27 18:32 UTC, wildpioneer commented on Task37/Program.cs
> +                        string normalizedString = sb.Replace("\t", " ").Replace("  ", " ").ToString();
Опять же - если обратить внимание на комментарий про нормализацию строки, то в определенных случаях начнет работать не верно весь алгоритм. Но по сути - если исправить нормализацию все остальное отлично

2023-12-01 14:46 UTC, poluni commented on Task31/Program.cs
> +                    reoplacedLine = line.Replace("test", "testing");
Исправлено в f1a987a7b9d3288bde39f57ff929330c9c3bda9b

2023-12-01 15:13 UTC, poluni commented on Task35/Program.cs
> +                foreach (Match matchItem in matches)
Исправлено в 97777f0291edd4b8218014b5d591015ce693c367

2023-12-01 15:18 UTC, poluni commented on Task35/Program.cs
> +                    else Console.WriteLine();
Исправлено в d0fa9eabb3dac329beeddb3364cb12927d5382ec

2023-12-01 16:30 UTC, poluni commented on Task31/Program.cs
> +            FileInfo fileInfo = new FileInfo(@"D:\git-auto\TMS_Auto\Task31\data.txt");
Исправлено в 94828c3597c74e89fd508a33bce304fa0111fb00

2023-12-01 16:57 UTC, poluni commented on Task34/Program.cs
> +            int positionOfRemove = inputLine.Length - removeWord.Length;
Исправлено в b25eedeb7b7e835bd7244063d7e9e34072dd1017

2023-12-02 15:11 UTC, poluni commented on Task37/Program.cs
> +                string[] words = new string[] { };
Исправлено в 402cab119695a8926a78059ca41e9c83e1045da5

2023-12-02 16:11 UTC, poluni commented on Task36/Program.cs
> +                        string word = sb.Replace("\t", " ").Replace("  ", " ").ToString();
Исправлено в 946d4c9a868fe98941ae5844efec362d28cf308a

2023-12-02 16:12 UTC, poluni commented on Task37/Program.cs
> +                        string normalizedString = sb.Replace("\t", " ").Replace("  ", " ").ToString();
Исправлено в 946d4c9a868fe98941ae5844efec362d28cf308a

2023-12-02 16:30 UTC, poluni commented on Task36/Program.cs
> +                        string word = sb.Replace("\t", " ").Replace("  ", " ").ToString();
Исправлено в a0da2cf462312d813679a3272894d3a54439d8cc

2024-01-29 10:10 UTC, wildpioneer commented
Проверено

2024-01-29 10:10 UTC, closed without merging